const actionTypes = {
    GET_HOME: 'GET_HOME',
    // GET_BANNERS: 'GET_BANNERS',
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
    SET_CUR_ALBUM_ID: 'SET_CUR_ALBUM_ID',
    SET_RECENT: 'SET_RECENT',
    //music
    PLAY: 'PLAY',
    PLAYLIST: 'PLAYLIST',

    //user
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    GET_CURRENT: 'GET_CURRENT',

    SEARCH: 'SEARCH',

}

export default actionTypes;